# Generated by Django 2.1.7 on 2019-02-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('photo', models.FileField(null=True, upload_to='mentee/', verbose_name='')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
